/* scripts/wipe-users-and-sim-data.ts
   Hard reset utility that removes every user account along with the
   simulation artifacts generated by seed-realistic-users-fast.ts.
   Run this before reseeding to guarantee a clean slate.
*/

import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient() as any;

type Step = {
  label: string;
  run: () => Promise<{ count?: number } | void>;
};

const steps: Step[] = [
  { label: "Token candles", run: () => prisma.tokenCandle.deleteMany({}) },
  { label: "Token price ticks", run: () => prisma.tokenPriceTick.deleteMany({}) },
  { label: "Token purchases", run: () => prisma.tokenPurchase.deleteMany({}) },
  { label: "Wallet deposits", run: () => prisma.walletDeposit.deleteMany({}) },
  { label: "Wallet addresses", run: () => prisma.walletAddress.deleteMany({}) },
  { label: "User wallets", run: () => prisma.userWallet.deleteMany({}) },
  { label: "Token holdings", run: () => prisma.userTokenHolding.deleteMany({}) },
  { label: "Profile snapshots", run: () => prisma.profileSnapshot.deleteMany({}) },

  { label: "Challenge daily stats", run: () => prisma.challengeDailyStat.deleteMany({}) },
  { label: "Challenge accounts", run: () => prisma.challengeAccount.deleteMany({}) },

  { label: "Resource progress entries", run: () => prisma.resourceProgress.deleteMany({}) },
  { label: "Student progress rows", run: () => prisma.studentProgress.deleteMany({}) },
  { label: "Daily activities", run: () => prisma.dailyActivity.deleteMany({}) },
  { label: "Course reviews", run: () => prisma.courseReview.deleteMany({}) },
  { label: "User badges", run: () => prisma.userBadge.deleteMany({}) },

  { label: "Community access flags", run: () => prisma.communityAccess.deleteMany({}) },
  { label: "Broker signups", run: () => prisma.brokerSignup.deleteMany({}) },

  { label: "Prize winners", run: () => prisma.prizeWinner.deleteMany({}) },
  { label: "Prize draws", run: () => prisma.prizeDraw.deleteMany({}) },

  { label: "Messages", run: () => prisma.message.deleteMany({}) },
  { label: "Conversations", run: () => prisma.conversation.deleteMany({}) },
  { label: "Quiz attempts", run: () => prisma.quizAttempt.deleteMany({}) },
  { label: "Bot feedback entries", run: () => prisma.botFeedback.deleteMany({}) },
  { label: "Event logs", run: () => prisma.event.deleteMany({}) },

  { label: "Account confirmation codes", run: () => prisma.accountConfirmCode.deleteMany({}) },
  { label: "Password reset tokens", run: () => prisma.password_reset_tokens.deleteMany({}) },
  { label: "Refresh tokens", run: () => prisma.refresh_tokens.deleteMany({}) },

  { label: "Referral rewards", run: () => prisma.referralReward.deleteMany({}) },
  { label: "Affiliates", run: () => prisma.affiliate.deleteMany({}) },
  { label: "Promo redemptions", run: () => prisma.promoRedemption.deleteMany({}) },

  { label: "Purchases", run: () => prisma.purchase.deleteMany({}) },

  {
    label: "Reset token sale progress",
    run: () =>
      prisma.tokenSale.updateMany({
        data: { soldSupply: BigInt(0), updatedAt: new Date() } as any,
      }),
  },

  { label: "Users", run: () => prisma.users.deleteMany({}) },
];

async function main() {
  console.log("⚠️  Wiping all users and simulation data...\n");

  for (const step of steps) {
    try {
      const result = await step.run();
      const count =
        result && typeof result === "object" && "count" in result ? (result as any).count : undefined;
      const suffix = typeof count === "number" ? ` (${count})` : "";
      console.log(`• ${step.label}${suffix}`);
    } catch (error) {
      console.error(`✗ ${step.label} failed`, error);
      throw error;
    }
  }

  console.log("\n✅ All data cleared successfully.");
}

main()
  .catch((error) => {
    console.error("❌ Wipe failed:", error);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
